
CPPFLAGS = -I..
CFLAGS = -Wall -fPIC -g
LDFLAGS = -shared
CC = gcc

LIB_SRC=dummyDev.c

LIB_OBJS = ${LIB_SRC:.c=.o}

LIB = libdummyDev.dylib

DEPS = $(LIB_OBJS:.o=.d) 

${LIB}: ${LIB_OBJS}
	$(CC) -dynamiclib $(CFLAGS) -o $@ ${LIB_OBJS} 

clean:
	rm -f test ${LIB} ${LIB_OBJS} $(DEPS)

-include $(DEPS) 

%.o: %.c
	gcc -MM $(CPPFLAGS) $(CXXFLAGS) $*.c > $*.d
	gcc $(CPPFLAGS) $(CXXFLAGS) -c $*.c -o $*.o
