#!/bin/sh

export POWERAPI_DEBUG=15

CONFIG=${HOME}/pwrGIT/working/examples/config/xtpmNode.py

pwrdaemon \
--srvr.rtrHost=localhost \
--srvr.rtrPort=15001 \
--srvr.pwrApiConfig=$CONFIG \
--srvr.pwrApiRoot=plat.cab0.board0.node0
