#!/bin/sh


export POWERAPI_DEBUG=15

CONFIG=${HOME}/pwrGIT/working/examples/config/xtpmNode.py

pwrdaemon \
--rtr.clientPort=15000 \
--rtr.serverPort=15001 \
--rtr.routerType=tree \
--rtr.routerId=0 \
--rtr.routeTable=routeTable.txt \
--rtr.pwrApiConfig=$CONFIG
