.\" Manpage for pwrapi
.\" Contact ddeboni@sandia.gov to correct errors or typos
.TH PWRAPI 8 "28 May 2015" Linux "pwrapi man page"
.SH NAME
pwrapi\- Power API measurement and control utility
.SH SYNOPSIS
\fBpwrapi\fP [ -s \fIsamples\fP ] [ -f \fIfrequency\fP ]
[ -a \fIattribute\fP ] [ -h ]
.SH DESCRIPTION
\fBpwrapi\fP is a command line utility for communicating monitor
and control commands through the Power API
.SH OPTIONS
.IP \fB-s\fP
number of samples to collect (default is 1, 0 for infinite)
.IP \fB-f\fP
frequency of collection (default is 1Hz, 0 for off)
.IP \fB-h\fP
usage information
.SH "SEE ALSO"
pwrgrp (8), pwrgen (8), pwrdmp (8)
.SH BUGS
No known bugs
.SH AUTHOR
David DeBonis (ddeboni@sandia.gov)
