.\" Manpage for pwrdmp
.\" Contact ddeboni@sandia.gov to correct errors or typos
.TH PWRDMP 8 "28 May 2015" Linux "pwrdmp man page"
.SH NAME
pwrdmp\- Power API measurement and control utility
.SH SYNOPSIS
\fBpwrdmp\fP [ -s \fIsamples\fP ] [ -f \fIfrequency\fP ]
[ -r \fI[range]\fP ] [ -h ]
.SH DESCRIPTION
\fBpwrdmp\fP is a command line utility for dumping measurment
and control commands available through the Power API to objects
.SH OPTIONS
.IP \fB-t\fP
type of objects to print (all if not specified)
.IP \fB-h\fP
usage information
.SH "SEE ALSO"
pwrapi (8), pwrgrp (8), pwrgen (8)
.SH BUGS
No known bugs
.SH AUTHOR
David DeBonis (ddeboni@sandia.gov)
