.\" Manpage for pwrsrv
.\" Contact ddeboni@sandia.gov to correct errors or typos
.TH PWRGEN 8 "28 May 2015" Linux "pwrsrv man page"
.SH NAME
pwrsrv\- Power API measurement and control daemon
.SH SYNOPSIS
\fBpwrsrv\fP [hostname]
.SH DESCRIPTION
\fBpwrsrv\fP is a daemon for allowing distributed Power API
calls over RPC with each node requiring a daemon process
.SH OPTIONS
.SH "SEE ALSO"
pwrapi (8), pwrgrp (8), pwrgen (8), pwrdmp (8)
.SH BUGS
No known bugs
.SH AUTHOR
David DeBonis (ddeboni@sandia.gov)
